[package]
name = "GoL"
version = "0.1.0"
authors = ["dhad05 <degeawapsh@gmail.com>"]

[dependencies]
gdk = "0.3.0"
cairo-rs = "0.0.8"
rand = "0.3"
glib = "0.0.8"
gdk-sys = "0.3.0"

[dependencies.gtk]
version = "0.0.7"
features = ["v3_16"]
