[package]
name = "GoL"
version = "0.1.0"
authors = ["dhad05 <degeawapsh@gmail.com>"]

[dependencies]
gdk = "0.5.3"
cairo-rs = "0.1.3"
rand = "0.3"

[dependencies.gtk]
version = "0.1.3"
features = ["v3_16"]
